theme: minima
title: Mi primer sitio web con GitHubPages y jekyll
author: Adri치n Gonz치lez Galv치n
email: alu0101321219@ull.edu.es
description: > # this means to ignore newlines until "baseurl:"
  Esta es la descripci칩n de mi primer sitio web xd. Muy simple, pero es lo que hay.
  Ya la iremos mejorando.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  alu0101321219 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
